FROM harbor.narvanventures.com/dockerhub/confluentinc/cp-kafka-connect:7.3.1
USER root

# Use apk (Alpine Package Keeper) to install unzip and curl
RUN apk add --no-cache curl unzip && \
    curl -L -o /tmp/clickhouse-kafka-connect.zip https://github.com/ClickHouse/clickhouse-kafka-connect/releases/download/v1.3.2/clickhouse-kafka-connect-v1.3.2.zip && \
    unzip /tmp/clickhouse-kafka-connect.zip -d /tmp/clickhouse-kafka-connect && \
    mkdir -p /usr/share/confluent-hub-components/clickhouse-kafka-connect/lib/ && \
    cp /tmp/clickhouse-kafka-connect/clickhouse-kafka-connect-*-all.jar /usr/share/confluent-hub-components/clickhouse-kafka-connect/lib/ && \
    rm -rf /tmp/clickhouse-kafka-connect /tmp/clickhouse-kafka-connect.zip

USER appuser
